version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
      - "8083:8083" # MQTT over WebSockets (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: server
    ports:
      - "9999:9999"
    depends_on:
      - mosquitto
    volumes:
      - ./mosquitto/log:/usr/src/app/mosquitto/log
    environment:
      - PORT=9999
      - SERVER_MQTT_CONNECTION_STRING=mqtt://username:password@mosquitto:1883
      - SERVER_MQTT_LOG_FILE=mosquitto/log/mosquitto.log

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
      args:
        - VITE_CLIENT_MQTT_CONNECTION_STRING=ws://username:password@127.0.0.1:8083
        - VITE_CLIENT_HTTP_CONNECTIONS=http://127.0.0.1:9999
    container_name: client
    volumes:
      - ./src/client/dist:/usr/src/app/src/client/dist
