version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
      - "9001:9001" # MQTT over WebSockets (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: server
    ports:
      - "9999:8080"
    depends_on:
      - mosquitto
    volumes:
      - ./mosquitto/log:/usr/src/app/mosquitto/log
    environment:
      - SERVER_MQTT_CONNECTION_STRING=mqtt://username:password@mosquitto:1883
      - SERVER_MQTT_LOG_FILE=mosquitto/log/mosquitto.log

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: client
    ports:
      - "8080:80"
    depends_on:
      - mosquitto
      - server
    environment:
      - NGINX_PORT=80
