export enum SHIFTR_CLONE_TOPIC {
  DISCONNECT = "SHIFTR_CLONE/DISCONNECT",
  CONNECT = "SHIFTR_CLONE/CONNECT",
  SUBSCRIBE = "SHIFTR_CLONE/SUBSCRIBE",
  UNSUBSCRIBE = "SHIFTR_CLONE/UNSUBSCRIBE",
  PUBLISH = "SHIFTR_CLONE/PUBLISH",
}
